version: '3.5'
services:
  nginx:
    env_file:
      - .env.prod

  php:
    image: symfony-skeleton-php:latest
    env_file:
      - .env.prod

  code:
    image: symfony-skeleton-code:latest
    env_file:
      - .env.prod

  postgress:
    env_file:
      - .env.prod

  adminer:
    env_file:
      - .env.prod

  redis:
    env_file:
      - .env.prod

  exim:
    image: symfony-skeleton-exim:latest
    env_file:
      - .env.prod

networks:
  local:
    name: ${NETWORK}

volumes:
  appdir:
    driver: local
  dbdata:
    driver: local
  redisdata:
    driver: local
  eximdata:
    driver: local